### PR TITLE
feat: handle minimal PSCI HVC exits

### LINKED ISSUE #252: feat: handle minimal PSCI HVC exits for arm64 boot
## Background

Parent issue #3 tracks the long-term goal of making `bangbang` a macOS/Apple Silicon Firecracker-compatible VMM. The current arm64 FDT advertises PSCI with `method = "hvc"`, so Linux is expected to issue HVC calls during early boot.

While implementing #250, the saved guest boot smoke scaffold reached the pinned Firecracker kernel but failed on the first HVC exit:

```text
guest boot smoke run-loop should not fail before marker: RunStep { steps_completed: 0, source: VcpuExitResolve(MmioDecode { exit: HvfExceptionExit { syndrome: 1509949440, virtual_address: 0, physical_address: 0 }, source: UnsupportedExceptionClass { exception_class: 22 } }) }
```

Exception class `0x16` is an AArch64 HVC instruction trap. This means the guest is following the advertised PSCI interface, but the HVF runner currently treats the exit as an unsupported MMIO decode failure.

## Requirement

Add the minimal PSCI HVC handling needed for a single-vCPU arm64 Linux guest to continue booting far enough for the guest boot smoke path in #250.

This should be a small HVF guest-exit capability PR, not a complete PSCI or multi-vCPU implementation.

## Acceptance criteria

- Decode AArch64 HVC exception exits as a typed HVF exit instead of routing them through MMIO decode.
- Route HVC exits through the runner/run-loop path without breaking existing MMIO, virtual timer, cancel, and unknown-exit behavior.
- Implement a minimal PSCI handler for the calls needed by the pinned Firecracker arm64 kernel during early single-vCPU boot.
- Return PSCI `NOT_SUPPORTED` for unsupported functions rather than failing the runner unexpectedly.
- Write the PSCI return value to the guest according to the ARM SMCCC/PSCI calling convention.
- Advance or resume guest execution correctly after the trapped HVC instruction, depending on how Hypervisor.framework reports the vCPU state.
- Add focused unit tests for HVC decode, runner classification, supported PSCI calls, unsupported calls, and guest register/PC behavior.
- Document the limited PSCI scope and explicitly defer full PSCI, CPU hotplug, reset/off policy, and multi-vCPU semantics.

## Relevant files and decisions

- Parent issue: #3
- Required by: #248
- Blocks: #250
- `crates/runtime/src/fdt.rs`: advertises PSCI `method = "hvc"` and CPU `enable-method = "psci"`.
- `crates/hvf/src/exit.rs`: currently decodes exception exits only as MMIO data aborts.
- `crates/hvf/src/runner.rs`: currently maps exception exits through MMIO handling and returns an error for HVC exception class `0x16`.
- `crates/hvf/src/vcpu.rs`: owns guest register access and boot-register setup.
- Saved WIP branch: `feat/issue-250-guest-boot-smoke` contains the #250 scaffold that exposed this blocker.

## Out of scope

- Full PSCI specification coverage.
- Multi-vCPU `CPU_ON` behavior beyond a safe unsupported response unless needed for the single-vCPU boot path.
- Public API changes or serial streaming.
- Guest boot smoke artifact generation; that remains in #250.

## Open questions

- Which exact PSCI calls does the pinned Firecracker kernel issue before reaching userspace?
- Should unsupported shutdown/reset calls remain `NOT_SUPPORTED` for now, or map to a terminal run-loop outcome in a later issue?

### PR DESCRIPTION
**Pull request by seven332**
## Summary

- Decode arm64 HVC exception exits as typed HVF exits instead of sending them through MMIO decode.
- Add a minimal `HVC #0` PSCI responder for early single-vCPU boot probing, writing return values back to X0 and returning `NOT_SUPPORTED` for nonzero HVC immediates.
- Let the internal boot run loop continue after handled HVC exits, and document the limited PSCI scope.

## Scope

This is intentionally not a full PSCI implementation. CPU hotplug, system reset/off semantics, and full SMCCC handling remain out of scope.

While validating against the saved #250 smoke scaffold, the original HVC blocker advanced to a later SMC blocker. That follow-up is tracked in #253.

Closes #252

## Verification

- `cargo fmt --all -- --check`
- `cargo check --workspace --all-targets --all-features --locked`
- `cargo test --workspace --all-targets --all-features --locked --exclude bangbang-hvf`
- `cargo test -p bangbang-hvf --lib --all-features --locked`
- `scripts/run-hvf-tests.sh --allow-unsupported`
- `cargo clippy --workspace --all-targets --all-features --locked -- -D warnings`
- `RUSTDOCFLAGS="-D warnings" cargo doc --workspace --all-features --no-deps --locked`
- Temporarily applied this diff on top of `feat/issue-250-guest-boot-smoke` and ran `scripts/run-guest-boot-smoke.sh --allow-unsupported`; the original HVC failure moved forward to the SMC failure now tracked by #253.

### CODE REVIEW

**Comment by seven332** [comment]
## Code Review: PR #254

### Summary

Reviewed the HVC exit decode, minimal PSCI responder, runner dispatch, boot-loop behavior, documentation, and tests.

### Findings

- P1 `crates/hvf/src/psci.rs:9` `MIGRATE_INFO_TYPE` reports the wrong trusted-OS migration type.

  Impact: The responder returns `0` for `MIGRATE_INFO_TYPE` while naming and documenting it as no trusted-OS migration. In PSCI/Linux semantics, `0` means a uniprocessor trusted OS requires migration; Linux can then issue `MIGRATE_INFO_UP_CPU`, which this PR intentionally does not implement. This exposes wrong guest-visible PSCI behavior and contradicts the PR docs/tests.

  Recommendation: Return the PSCI value for "no trusted OS migration / MP or no trusted OS" (`2`) and update the constant name, tests, and compatibility docs to match.

### Testing

- Ran `cargo test -p bangbang-hvf --lib --all-features --locked`.
- Reviewed the PR body's listed validation from the review-loop pass; full smoke is still blocked by #253 after the HVC blocker advances.

### Verdict

Changes Requested

**Comment by seven332** [comment]
Fixed the PSCI `MIGRATE_INFO_TYPE` review finding in `ea15593`.

- `MIGRATE_INFO_TYPE` now returns `2`, the PSCI value for a trusted OS that is MP-capable or not present, where migration is not required.
- Updated the constant/test naming and compatibility documentation to match.

Verification run after the fix:

- `cargo fmt --all -- --check`
- `cargo test -p bangbang-hvf --lib --all-features --locked`
- `cargo check --workspace --all-targets --all-features --locked`
- `cargo clippy --workspace --all-targets --all-features --locked -- -D warnings`
- `RUSTDOCFLAGS="-D warnings" cargo doc --workspace --all-features --no-deps --locked`

**Comment by seven332** [comment]
## Code Review: PR #254

### Summary

Reviewed the final PR head after `ea15593`. The HVC exit classification, minimal PSCI-over-HVC responses, nonzero immediate handling, runner dispatch path, run-loop continuation, tests, and compatibility docs are consistent with #252 scope.

### Findings

No findings.

### Testing

Current-head validation was covered by the review loop:

- `cargo fmt --all -- --check`
- `cargo check --workspace --all-targets --all-features --locked`
- `cargo test --workspace --all-targets --all-features --locked --exclude bangbang-hvf`
- `cargo test -p bangbang-hvf --lib --all-features --locked`
- `scripts/run-hvf-tests.sh --allow-unsupported`
- `cargo clippy --workspace --all-targets --all-features --locked -- -D warnings`
- `RUSTDOCFLAGS="-D warnings" cargo doc --workspace --all-features --no-deps --locked`

The temporary #250 smoke overlay now advances past the original HVC blocker and reaches the SMC blocker tracked by #253.

### Verdict

LGTM
